//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba.Infrastructure.Crosscutting.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Prueba.Infrastructure.Crosscutting.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} está duplicado..
        /// </summary>
        public static string EntidadDuplicada {
            get {
                return ResourceManager.GetString("EntidadDuplicada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution of method api.
        /// </summary>
        public static string ExecutionMethodApi {
            get {
                return ResourceManager.GetString("ExecutionMethodApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occurred..
        /// </summary>
        public static string GenericError {
            get {
                return ResourceManager.GetString("GenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header {0} is mandatory..
        /// </summary>
        public static string HeaderMandatory {
            get {
                return ResourceManager.GetString("HeaderMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max lenght of {0} is {1}..
        /// </summary>
        public static string MaxLenght {
            get {
                return ResourceManager.GetString("MaxLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max length of {0} is {1}..
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max length of {0} is 100..
        /// </summary>
        public static string MaxLength_100 {
            get {
                return ResourceManager.GetString("MaxLength_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max length of {0} is 150..
        /// </summary>
        public static string MaxLength_150 {
            get {
                return ResourceManager.GetString("MaxLength_150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max length of {0} is 20..
        /// </summary>
        public static string MaxLength_20 {
            get {
                return ResourceManager.GetString("MaxLength_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max length of {0} is 200..
        /// </summary>
        public static string MaxLength_200 {
            get {
                return ResourceManager.GetString("MaxLength_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max length of {0} is 250..
        /// </summary>
        public static string MaxLength_250 {
            get {
                return ResourceManager.GetString("MaxLength_250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max length of {0} is 3..
        /// </summary>
        public static string MaxLength_3 {
            get {
                return ResourceManager.GetString("MaxLength_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max length of {0} is 320..
        /// </summary>
        public static string MaxLength_320 {
            get {
                return ResourceManager.GetString("MaxLength_320", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max length of {0} is 800..
        /// </summary>
        public static string MaxLength_800 {
            get {
                return ResourceManager.GetString("MaxLength_800", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found resource..
        /// </summary>
        public static string NotFoundResource {
            get {
                return ResourceManager.GetString("NotFoundResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is mandatory..
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor del Id debe se mayor a cero..
        /// </summary>
        public static string ValorIdMayorACero {
            get {
                return ResourceManager.GetString("ValorIdMayorACero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is wrong..
        /// </summary>
        public static string Wrong {
            get {
                return ResourceManager.GetString("Wrong", resourceCulture);
            }
        }
    }
}
